[workspace]
resolver = "2"

members = [
	"binary",
	"process_mining",
	"python_bridge",
	"java_bridge",
	"pm_wasm",
	"npm_wasm"
]

[profile.release.package.pm_wasm]
debug = true

[profile.release]
debug = false
strip = true
panic = 'abort'
opt-level = 3
lto = true
codegen-units = 1
